apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mcpjungle.fullname" . }}-mcp-servers
  labels:
    {{- include "mcpjungle.labels" . | nindent 4 }}
data:
  {{- range $key, $server := .Values.mcpServers }}
  {{ $key }}.json: |
    {
      "name": {{ $server.name | quote }},
      "transport": {{ $server.transport | quote }},
      "description": {{ $server.description | quote }},
      "url": {{ $server.url | quote }}
      {{- if $server.bearer_token }}
      ,"bearer_token": {{ $server.bearer_token | quote }}
      {{- end }}
      {{- if $server.command }}
      ,"command": {{ $server.command | quote }}
      {{- end }}
      {{- if $server.args }}
      ,"args": {{ $server.args | toJson }}
      {{- end }}
      {{- if $server.env }}
      ,"env": {{ $server.env | toJson }}
      {{- end }}
    }
  {{- end }}
