{{- if .Values.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "mcpjungle.fullname" . }}-secrets-manager
  labels:
    {{- include "mcpjungle.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "create", "update", "patch"]
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: ["{{ include "mcpjungle.fullname" . }}-admin-token"]
  verbs: ["get", "list", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "mcpjungle.fullname" . }}-secrets-manager
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mcpjungle.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "mcpjungle.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "mcpjungle.fullname" . }}-secrets-manager
  apiGroup: rbac.authorization.k8s.io
{{- end }}
